package com.example.quranfacts.data

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Mirrors app/src/main/assets/facts.json, which is generated by tools/build_content.py
 * (verse text and media are fetched and verified there, never typed by hand).
 */
@Serializable
data class FactsDoc(
    val schema: Int,
    val categories: List<Category>,
    val claimTypes: List<ClaimType>,
    val translations: Map<String, TranslationInfo>,
    /** 41:53, the Quran's own statement of what this app is about ("We will show them Our signs…"). */
    val intro: Verse? = null,
    val facts: List<Fact>,
)

/** The revelation of the Quran ended with the death of the Prophet ﷺ in 632 CE. Gaps are counted from here. */
const val REVELATION_END_YEAR = 632

@Serializable
data class Category(
    val id: String,
    val name: String,
    val tagline: String,
    val accent: String,
)

/** How strong the link between a verse and a discovery is. See ClaimTypes in the UI. */
@Serializable
data class ClaimType(
    val id: String,
    val label: String,
    val short: String,
    val description: String,
)

@Serializable
data class TranslationInfo(
    val edition: String,
    val translator: String,
    val language: String,
    /** The institution behind the translation, where it is an official one (shown under the translator). */
    val publisher: String = "",
    /** False if no fully trusted translation exists for the language: verses then show in English with an explanation. */
    val trusted: Boolean = true,
)

@Serializable
data class Verse(
    val surah: Int,
    val ayah: Int,
    val surahEn: String,
    val surahAr: String,
    val surahMeaning: String,
    val ar: String,
    val tr: Map<String, String>,
    /** Recitation (Mishary Alafasy) for this ayah. */
    val audio: String? = null,
) {
    val ref: String get() = "$surah:$ayah"
    val quranComUrl: String get() = "https://quran.com/$surah/$ayah"
}

@Serializable
data class Word(
    val ar: String,
    val tr: String,
    val en: String,
    val root: String,
)

@Serializable
data class Stat(
    val value: String,
    val label: String,
)

@Serializable
data class Discovery(
    @SerialName("when") val whenText: String,
    val who: String,
    /** The year the timeline places this discovery at (the start of `whenText`). */
    val year: Int? = null,
) {
    /** Years between the end of the revelation and this discovery, counted conservatively from 632 CE. */
    val yearsAfterRevelation: Int? get() = year?.let { it - REVELATION_END_YEAR }
}

@Serializable
data class Media(
    val type: String, // "image" | "video" | "audio"
    val url: String,
    val thumb: String,
    val big: String,
    val w: Int? = null,
    val h: Int? = null,
    val duration: Int = 0,
    val caption: String,
    val credit: String,
    val license: String,
    val page: String,
) {
    val isVideo: Boolean get() = type == "video"
    val isAudio: Boolean get() = type == "audio"
}

/** One step in how something was found out: who did what, when, and what it showed. */
@Serializable
data class ProofStep(
    val year: String,
    val title: String,
    val text: String,
    val media: Media? = null,
)

/** Where a verse's wording matches the finding, and where it does not or is contested. */
@Serializable
data class Fit(
    val fits: List<String> = emptyList(),
    val gaps: List<String> = emptyList(),
)

@Serializable
data class Source(
    val title: String,
    val url: String,
)

@Serializable
data class Fact(
    val id: String,
    val title: String,
    val hook: String,
    val category: String,
    val claimType: String,
    val widget: String? = null,
    val scienceHeading: String = "What science found",
    val verses: List<Verse>,
    val words: List<Word> = emptyList(),
    val science: List<String>,
    val stats: List<Stat> = emptyList(),
    val discovery: Discovery? = null,
    val proofHeading: String = "How it was found out",
    val proof: List<ProofStep> = emptyList(),
    val fit: Fit = Fit(),
    val media: List<Media> = emptyList(),
    val sources: List<Source> = emptyList(),
) {
    val heroImage: Media? get() = media.firstOrNull { !it.isVideo && !it.isAudio }
    val hasVideo: Boolean get() = media.any { it.isVideo }
    val primaryRef: String
        get() = verses.firstOrNull()?.let { "${it.surahEn} ${it.ref}" }.orEmpty()
}
