#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generates the Quran & Science brand assets from ONE geometry, so every size matches:

  app/src/main/res/drawable/ic_launcher_{background,foreground,monochrome}.xml   adaptive icon (vector)
  app/src/main/res/mipmap-*/ic_launcher{,_round}.webp                          icons for Android 7.x
  store/icon-512.png                                                           Google Play icon
  store/feature-graphic.png                                                    Google Play feature graphic (1024x500)

The idea: "We will show them Our signs (ayat) in the horizons (afaq)" (41:53). A gold eight-pointed star,
the app's ornament, rises over the glowing horizon of a planet at night.

Usage:  python3 tools/make_brand.py
"""
import math
import os

import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "app", "src", "main", "res")
STORE = os.path.join(ROOT, "store")

# ---- Geometry, in the adaptive icon's 108 x 108 units ---------------------------------------
SKY_TOP, SKY_BOTTOM = "#1D2D5E", "#080C19"
GLOW = ("#E2B865", 54, 70, 46)           # colour, centre x, centre y, radius
PLANET = (54, 129, 60)                    # centre x, centre y, radius (top edge at y = 69)
PLANET_TOP, PLANET_BOTTOM = "#16224A", "#05070F"
RIM_COLOR, RIM_WIDTH = "#F3D58C", 1.5
STAR = (54, 47, 16.5)                     # centre x, centre y, outer radius
STAR_TOP, STAR_BOTTOM = "#FBE3A6", "#CF9C45"
STAR_INNER = ("#B3FFF3D1", 0.5)          # a lighter star inside, turned 22.5 degrees: colour (ARGB), size
SPARKLES = [(22, 25, 0.6), (84, 19, 0.55), (91, 42, 0.42), (15, 50, 0.42), (70, 27, 0.36), (36, 15, 0.4),
            (79, 57, 0.32), (28, 60, 0.3), (60, 13, 0.3)]


def star_points(cx, cy, r, rotation=-90.0):
    """The Rub el Hizb: two squares, one turned 45 degrees. 16 points, alternating outer and inner.
    Same shape as starPath() in Ornament.kt."""
    inner = r * math.cos(math.radians(45)) / math.cos(math.radians(22.5))
    pts = []
    for k in range(16):
        a = math.radians(rotation + k * 22.5)
        rr = r if k % 2 == 0 else inner
        pts.append((cx + rr * math.cos(a), cy + rr * math.sin(a)))
    return pts


def hex_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


# ---- Vector drawables ----------------------------------------------------------------------------
def circle_path(cx, cy, r):
    return f"M{cx - r:.2f},{cy:.2f} a{r:.2f},{r:.2f} 0 1,0 {2 * r:.2f},0 a{r:.2f},{r:.2f} 0 1,0 {-2 * r:.2f},0"


def poly_path(pts):
    return "M" + " L".join(f"{x:.2f},{y:.2f}" for x, y in pts) + " Z"


VECTOR_HEAD = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/make_brand.py. Edit the script, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
"""


def linear(attr, x1, y1, x2, y2, stops):
    items = "\n".join(f'                <item android:color="{c}" android:offset="{o}" />' for o, c in stops)
    return f"""        <aapt:attr name="android:{attr}">
            <gradient android:type="linear" android:startX="{x1}" android:startY="{y1}" android:endX="{x2}" android:endY="{y2}">
{items}
            </gradient>
        </aapt:attr>"""


def write_vectors():
    gc, gx, gy, gr = GLOW
    bg = VECTOR_HEAD + f"""    <path android:pathData="M0,0h108v108h-108z">
{linear("fillColor", 54, 0, 54, 108, [(0, "#FF" + SKY_TOP[1:]), (1, "#FF" + SKY_BOTTOM[1:])])}
    </path>
    <path android:pathData="{circle_path(gx, gy, gr)}">
        <aapt:attr name="android:fillColor">
            <gradient android:type="radial" android:centerX="{gx}" android:centerY="{gy}" android:gradientRadius="{gr}">
                <item android:color="#70{gc[1:]}" android:offset="0" />
                <item android:color="#00{gc[1:]}" android:offset="1" />
            </gradient>
        </aapt:attr>
    </path>
""" + "".join(
        f'    <path android:fillColor="#CCFFFFFF" android:pathData="{circle_path(x, y, r)}" />\n' for x, y, r in SPARKLES
    ) + "</vector>\n"

    px, py, pr = PLANET
    sx, sy, sr = STAR
    inner_c, inner_f = STAR_INNER
    fg = VECTOR_HEAD + f"""    <path android:pathData="{circle_path(px, py, pr)}">
{linear("fillColor", 54, py - pr, 54, 108, [(0, "#FF" + PLANET_TOP[1:]), (1, "#FF" + PLANET_BOTTOM[1:])])}
    </path>
    <path android:pathData="{circle_path(px, py, pr)}" android:strokeWidth="{RIM_WIDTH}">
{linear("strokeColor", 4, 0, 104, 0, [(0, "#00" + RIM_COLOR[1:]), (0.5, "#FF" + RIM_COLOR[1:]), (1, "#00" + RIM_COLOR[1:])])}
    </path>
    <path android:pathData="{poly_path(star_points(sx, sy, sr))}">
{linear("fillColor", 54, sy - sr, 54, sy + sr, [(0, "#FF" + STAR_TOP[1:]), (1, "#FF" + STAR_BOTTOM[1:])])}
    </path>
    <path android:fillColor="{inner_c}" android:pathData="{poly_path(star_points(sx, sy, sr * inner_f, -67.5))}" />
</vector>
"""
    # Themed icons (Android 13+): one colour, the system tints it.
    mono = VECTOR_HEAD + f"""    <path android:fillColor="#FFFFFFFF" android:pathData="{poly_path(star_points(sx, sy, sr))}" />
    <path android:strokeColor="#FFFFFFFF" android:strokeWidth="{RIM_WIDTH + 0.6}"
        android:pathData="M18,{py - math.sqrt(pr * pr - 36 * 36):.2f} A{pr},{pr} 0 0,1 90,{py - math.sqrt(pr * pr - 36 * 36):.2f}" />
</vector>
"""
    for name, xml in (("ic_launcher_background", bg), ("ic_launcher_foreground", fg), ("ic_launcher_monochrome", mono)):
        with open(os.path.join(RES, "drawable", name + ".xml"), "w") as f:
            f.write(xml)


# ---- Raster rendering of the same geometry ------------------------------------------------------
def vertical_gradient(w, h, top, bottom, y0=0.0, y1=None):
    y1 = h if y1 is None else y1
    t = np.clip((np.arange(h, dtype=np.float32) - y0) / max(1.0, y1 - y0), 0, 1)[:, None, None]
    a, b = np.array(hex_rgb(top), np.float32), np.array(hex_rgb(bottom), np.float32)
    rgb = a + (b - a) * t
    return Image.fromarray(np.broadcast_to(rgb, (h, w, 3)).astype(np.uint8))


def paint_scene(w, h, unit, star, planet, glow, sparkles):
    """Paints the night sky, glow, sparkles, planet with rim, and star, in pixels. `unit` scales strokes."""
    img = vertical_gradient(w, h, SKY_TOP, SKY_BOTTOM).convert("RGBA")
    gc = GLOW[0]
    gx, gy, gr = glow
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float32)
    d = np.sqrt((xx - gx) ** 2 + (yy - gy) ** 2) / gr
    alpha = (np.clip(1 - d, 0, 1) ** 1.6 * 0.44 * 255).astype(np.uint8)
    layer = Image.new("RGBA", (w, h), hex_rgb(gc) + (0,))
    layer.putalpha(Image.fromarray(alpha))
    img = Image.alpha_composite(img, layer)

    draw = ImageDraw.Draw(img)
    for x, y, r in sparkles:
        draw.ellipse([x - r, y - r, x + r, y + r], fill=(255, 255, 255, 204))

    px, py, pr = planet
    body = vertical_gradient(w, h, PLANET_TOP, PLANET_BOTTOM, py - pr, min(h, py)).convert("RGBA")
    mask = Image.new("L", (w, h), 0)
    ImageDraw.Draw(mask).ellipse([px - pr, py - pr, px + pr, py + pr], fill=255)
    img.paste(body, (0, 0), mask)
    rim = Image.new("L", (w, h), 0)
    rw = RIM_WIDTH * unit
    ImageDraw.Draw(rim).ellipse([px - pr, py - pr, px + pr, py + pr], outline=255, width=max(1, int(round(rw))))
    fade = np.clip(1 - np.abs(np.arange(w, dtype=np.float32) - px) / (pr * 0.83), 0, 1)[None, :]
    rim_layer = Image.new("RGBA", (w, h), hex_rgb(RIM_COLOR) + (0,))
    rim_layer.putalpha(Image.fromarray((np.asarray(rim, np.float32) * fade).astype(np.uint8)))
    img = Image.alpha_composite(img, rim_layer.filter(ImageFilter.GaussianBlur(rw * 1.6)))
    img = Image.alpha_composite(img, rim_layer)

    sx, sy, sr = star
    star_mask = Image.new("L", (w, h), 0)
    ImageDraw.Draw(star_mask).polygon(star_points(sx, sy, sr), fill=255)
    img.paste(vertical_gradient(w, h, STAR_TOP, STAR_BOTTOM, sy - sr, sy + sr).convert("RGBA"), (0, 0), star_mask)
    inner_c, inner_f = STAR_INNER
    inner = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    ImageDraw.Draw(inner).polygon(star_points(sx, sy, sr * inner_f, -67.5),
                                  fill=hex_rgb("#" + inner_c[3:]) + (int(inner_c[1:3], 16),))
    return Image.alpha_composite(img, inner)


def render_icon(px_size):
    """The full 108-unit canvas (background + foreground) rendered at px_size, anti-aliased."""
    ss = 4
    n = px_size * ss
    u = n / 108.0
    scale = lambda t: tuple(v * u for v in t)
    img = paint_scene(n, n, u, scale(STAR), scale(PLANET), scale(GLOW[1:]), [scale(sp) for sp in SPARKLES])
    return img.resize((px_size, px_size), Image.LANCZOS)


def visible(px_size, units=76):
    """The part of the canvas a launcher actually shows (adaptive icons show the middle 72 of 108 units)."""
    big = render_icon(int(px_size * 108 / units) + 1)
    off = (big.width - px_size) // 2
    return big.crop((off, off, off + px_size, off + px_size))


def rounded(img, radius_frac):
    mask = Image.new("L", (img.width * 4, img.height * 4), 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, mask.width - 1, mask.height - 1], radius=int(mask.width * radius_frac), fill=255)
    out = img.copy()
    out.putalpha(mask.resize(img.size, Image.LANCZOS))
    return out


def circled(img):
    mask = Image.new("L", (img.width * 4, img.height * 4), 0)
    ImageDraw.Draw(mask).ellipse([0, 0, mask.width - 1, mask.height - 1], fill=255)
    out = img.copy()
    out.putalpha(mask.resize(img.size, Image.LANCZOS))
    return out


def write_legacy_mipmaps():
    for density, size in (("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)):
        d = os.path.join(RES, f"mipmap-{density}")
        os.makedirs(d, exist_ok=True)
        inner = int(size * 0.92)  # a little breathing room, like Android's own legacy icons
        art = visible(inner)
        for name, shaped in (("ic_launcher", rounded(art, 0.22)), ("ic_launcher_round", circled(art))):
            canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
            canvas.paste(shaped, ((size - inner) // 2, (size - inner) // 2), shaped)
            canvas.save(os.path.join(d, name + ".webp"), "WEBP", lossless=True)


def font(path, size, index=0):
    return ImageFont.truetype(path, size, index=index)


def write_store_graphics():
    os.makedirs(STORE, exist_ok=True)
    visible(512).convert("RGB").save(os.path.join(STORE, "icon-512.png"))

    # Feature graphic: the same night scene, wide, with the star on the left and the name on the right.
    ss = 3
    w, h = 1024 * ss, 500 * ss
    u = 13.0 * ss                                   # one icon unit, in feature-graphic pixels
    star = (215 * ss, 196 * ss, 96 * ss)
    planet = (512 * ss, (408 + 1500) * ss, 1500 * ss)   # a gentle arc whose top is low, at y = 408
    glow = (215 * ss, 400 * ss, 440 * ss)
    sparkles = [(x * ss, y * ss, r * ss) for x, y, r in
                [(70, 60, 3), (470, 40, 2.4), (930, 70, 2.2), (560, 140, 1.8), (980, 300, 1.8), (40, 260, 1.6), (720, 30, 1.6)]]
    scene = paint_scene(w, h, u * 0.7, star, planet, glow, sparkles).resize((1024, 500), Image.LANCZOS)
    d = ImageDraw.Draw(scene)
    serif = "/System/Library/Fonts/Supplemental/Georgia Bold.ttf"
    sans = "/System/Library/Fonts/Supplemental/Futura.ttc"
    gold = hex_rgb("#E9C77E")
    d.text((400, 140), "Quran & Science", font=font(serif, 60), fill=(255, 255, 255))
    d.text((403, 232), "Verses beside the discoveries", font=font(sans, 31), fill=gold)
    d.text((403, 274), "that came centuries later", font=font(sans, 31), fill=gold)
    d.text((404, 348), "VERSE  ·  DISCOVERY  ·  PROOF", font=font(sans, 20), fill=(200, 208, 230))
    scene.convert("RGB").save(os.path.join(STORE, "feature-graphic.png"))


if __name__ == "__main__":
    write_vectors()
    write_legacy_mipmaps()
    write_store_graphics()
    print("Wrote vector icon, legacy mipmaps, store/icon-512.png and store/feature-graphic.png")
